magnet/board/urls.py
from django.conf.urls import url

from . import views

app_name = 'board'

urlpatterns = [
    url(r'^scroll(?P<scroll_x>[0-9]+)-(?P<scroll_y>[0-9]+)$', views.index, name='index'),
    url(r'^$', views.index, name='index'),
    url(r'^reposition$', views.reposition, name='reposition'),
    url(r'^add_or_del_phrase$', views.add_or_del_phrase, name='add_or_del_phrase'),
    url(r'^login/(?P<error_code>[0-9]+)$', views.login_form, name='login_form'),
    url(r'^login$', views.login_form, name='login_form'),
    url(r'^login-(?P<error_code>[0-9]+)$', views.auth_login, name='login'),
    url(r'^logout$', views.auth_logout, name='logout'),
    url(r'^register-(?P<error_code>[0-9]+)$', views.auth_register, name='register')
]

magnet/magnet/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^board/', include('board.urls')),
    url(r'^admin/', admin.site.urls),
]

magnet/board/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.utils.encoding import python_2_unicode_compatible
from django.core.exceptions import ValidationError

import re

# Create your models here.
    
@python_2_unicode_compatible
class Phrase(models.Model):
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    pub_date = models.DateTimeField('date published')
    text = models.CharField(max_length=255)
    def __str__(self):
        return self.text

@python_2_unicode_compatible 
class Word(models.Model):
    phrase = models.ForeignKey(Phrase, on_delete=models.DO_NOTHING, default='%No phrase%')
    text = models.SlugField(max_length=50)
    pos_x = models.FloatField(default=0)
    pos_y = models.FloatField(default=0)
    used = models.BooleanField(default=False)
    def __str__(self):
        return self.text
    def clean(self):
        if re.search(r"\s", self.text):
            raise ValidationError('spaces in text are not allowed')

magnet/board/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.forms import EmailField, SlugField, CharField, ValidationError, PasswordInput
from operator import itemgetter

from .models import Word, Phrase

def index(request, scroll_x=0, scroll_y=0):
    if request.user.is_authenticated():
        wordlist = Word.objects.all()
        colors = ['#1E90FF', '#6495ED', '#9932CC', '#5F9EA0', '#00BFFF',
                  '#7FFFD4', '#DB7093', '#00CED1', '#ADD8E6', '#1E90FF']
        phrasedict = {}
        for i, phrase in enumerate(Phrase.objects.all()):
            if phrase.word_set.count()>0 and phrase.text != '%No phrase%':
                phrasedict[phrase] = colors[i%10]
        context = {'wordlist': wordlist, 'phrasedict': phrasedict,
        'init_scroll_x': scroll_x, 'init_scroll_y': scroll_y}
        return render(request, 'board/index.html', context)
    else:
        return HttpResponseRedirect(reverse('board:login_form'))
        
def login_form(request, error_code=None):
    context = {'error_code': error_code}
    return render(request, 'board/login.html', context)
        
def auth_login(request, error_code):
    username = request.POST['login_name']
    password = request.POST['login_pass']
    user = authenticate(username=username, password=password)
    if user is not None:
        login(request, user)
        scroll_x = 0
        scroll_y = 0
        return HttpResponseRedirect(reverse('board:index', args=(scroll_x, scroll_y)))
    else:
        error_code = 1
        return HttpResponseRedirect(reverse('board:login_form', args=(error_code, )))

def auth_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('board:login_form'))
        
def auth_register(request, error_code):
    username_f = SlugField(max_length=30)
    password_f = CharField(max_length=30, widget=PasswordInput)
    email_f = EmailField()
    username = request.POST.get('reg_name', None)
    password = request.POST.get('reg_pass', None)
    email = request.POST.get('reg_email', None)
    for field, value in [(username_f, username), (password_f, password), (email_f, email)]:
        try:
            field.clean(value)
        except ValidationError:
            error_code = 2
            return HttpResponseRedirect(reverse('board:login_form', args=(error_code, )))
            break
    else:
        if User.objects.filter(username=username).exists():
            error_code = 3
            return HttpResponseRedirect(reverse('board:login_form', args=(error_code, ))) 
        else:
            User.objects.create_user(username=username, email=email, password=password)
            user = authenticate(username=username, password=password)
            login(request, user)
            return HttpResponseRedirect(reverse('board:index', args=(0, 0)))
            
def reposition(request):
    word = Word.objects.get(pk = request.POST.get('word_id'))
    word.pos_x = request.POST.get('pos_x')
    word.pos_y = request.POST.get('pos_y')
    word.save()
    scroll_x = request.POST.get('scroll_x')
    scroll_y = request.POST.get('scroll_y')
    return HttpResponseRedirect(reverse('board:index', args=(scroll_x, scroll_y)))

def add_or_del_phrase(request):
    mode = request.POST.get('mode')
    id_list = request.POST.get('phrase').split()
    scroll_x = request.POST.get('scroll_x_2')
    scroll_y = request.POST.get('scroll_y_2')
    if mode == 'add':
        words = []
        for el in id_list:
            word = Word.objects.get(pk=int(el))
            words.append([word.id, word.text, word.pos_x, word.pos_y])
        words_sorted = sorted(words, key=itemgetter(3,2)) # sort words in screen reading order
        for i, w in enumerate(words_sorted):
            if i == 0:
                phrase_text = w[1]
            else:
                phrase_text += (" "+w[1])
        phrase = Phrase(created_by=request.user, pub_date=timezone.now(),
        text=phrase_text)
        phrase.save()
        for el in id_list:
            word = Word.objects.get(pk=int(el))
            word.phrase = phrase
            word.used = True
            word.save()
    elif mode == 'del':
        for el in id_list:
            word = Word.objects.get(pk=int(el))
            word.used = False
            word.phrase = Phrase.objects.get(text='%No phrase%')
            word.save()
    return HttpResponseRedirect(reverse('board:index', args=(scroll_x, scroll_y)))

magnet/board/templates/board/login.html
<!DOCTYPE html>
<html >
<head>
  <meta charset="UTF-8">
  <title>Fridge Board: Login Form</title>
  
      <style type="text/css">
        @import url(https://fonts.googleapis.com/css?family=Tahoma:300);

        .login-page {
          width: 360px;
          padding: 5% 0 0;
          margin: auto;
        }
        .form {
          position: relative;
          z-index: 1;
          background: #FFFFFF;
          max-width: 360px;
          margin: 0 auto 10px;
          padding: 40px;
          text-align: center;
          border: 4px double black;
        }
        .form input {
          font-family: "Tahoma", sans-serif;
          outline: 0;
          background: #f2f2f2;
          width: 100%;
          border: 0;
          margin: 0 0 15px;
          padding: 15px;
          box-sizing: border-box;
          font-size: x-large;
        }
        .form button {
          font-family: "Tahoma", sans-serif;
          outline: 0;
          background: #4CAF50;
          width: 100%;
          border: 0;
          padding: 15px;
          color: #FFFFFF;
          font-size: x-large;
          -webkit-transition: all 0.3 ease;
          transition: all 0.3 ease;
          cursor: pointer;
        }
        .form button:hover,.form button:active,.form button:focus {
          background: #43A047;
        }
        .form .message {
          margin: 15px 0 0;
          color: #b3b3b3;
          font-size: large;
          font-family: "Tahoma", sans-serif;
        }
        .form .message2 {
          margin: 15px 0 0;
          color: #DC143C;
          font-size: x-large;
          font-family: "Tahoma", sans-serif;
        }
        .form .caption {
          font-family: "Tahoma", sans-serif;
          border: 5px dotted #000;
          text-decoration: none;
          background: #1E90FF;
          width: 85%;
          padding: 15px;
          color: #000000;
          font-size: xx-large;
        }
        .form .message a {
          color: #4CAF50;
          text-decoration: none;
        }
        .form .register-form {
          display: none;
        }
        .container {
          position: relative;
          z-index: 1;
          max-width: 300px;
          margin: 0 auto;
        }
        .container:before, .container:after {
          content: "";
          display: block;
          clear: both;
        }
        .container .info {
          margin: 50px auto;
          text-align: center;
        }
        .container .info h1 {
          margin: 0 0 15px;
          padding: 0;
          font-size: 36px;
          font-weight: 300;
          color: #1a1a1a;
        }
        .container .info span {
          color: #4d4d4d;
          font-size: 12px;
        }
        .container .info span a {
          color: #000000;
          text-decoration: none;
        }
        .container .info span .fa {
          color: #EF3B3A;
        }
        body {
          background: #f2f2f2;    
        }
      </style>

</head>

<body>
  <div class="login-page">
  <div class="form">
    <p class="caption">fridge board</p><p></p>
    {% if error_code == '1' %}
    <p class="message2">user doesn't exist<br>try again or create a new account</p><p></p>
    {% elif error_code == '2' %}
    <p class="message2">invalid input<br>try again</p><p></p>
    {% elif error_code == '3' %}
    <p class="message2">this user is already registered</p><p></p>
    {% endif %}
    <form class="register-form" id="register-form" action="{% url 'board:register' 0 %}" method="post">
      {% csrf_token %}
      <input type="text" name="reg_name" placeholder="name"/>
      <input type="password" name="reg_pass" placeholder="password"/>
      <input type="text" name="reg_email" placeholder="email address"/>
      <button>create</button>
      <p class="message">already registered? <a href="#">sign in</a></p>
    </form>
    <form class="login-form" id="login-form" action="{% url 'board:login' 0 %}" method="post">
      {% csrf_token %}
      <input type="text" name="login_name" placeholder="username"/>
      <input type="password" name="login_pass" placeholder="password"/>
      <button>login</button>
      <p class="message">not registered?<br><a href="#">create an account</a></p>
    </form>
  </div>
</div>
  <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>

    <script type="text/javascript">
        $('.message a').click(function(){
           $('form').animate({height: "toggle", opacity: "toggle"}, "slow");
        });
    </script>

</body>
</html>